from enum import Enum


class DataType(Enum):
    UNKNOWN = "UNKNOWN"

    PROFILE_15MIN = "PROFILE_15MIN"

    MONTHLY_SUMMARY = "MONTHLY_SUMMARY"

    DAILY_SUMMARY = "DAILY_SUMMARY"

    PRODUCTION = "PRODUCTION"

    CONSUMPTION = "CONSUMPTION"

    BATTERY = "BATTERY"

    WEATHER = "WEATHER"